# Partimos de una base oficial de ubuntu :latest
FROM ubuntu:18.04

#ejecutamos pip para instalar las dependencias en el contenedor
RUN apt-get update && apt-get install -y apache2 && apt-get clean && rm -rf /var/lib/apt/lists/*

Declaramos una variable de entorno

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_LOG_DIR /var/lock/apache2

#Ejecutamos crear carpeta en el contenedor
RUN mkdir -p $APACHE_RUN_DIR 
RUN mkdir -p $APACHE_LOCK_DIR
RUN mkdir -p $APACHE_LOG_DIR

#Copiamos todos los archivos de la carpeta local al contenedor
COPY index.html /var/www/html

#Indicamos que este contenedor se comunica por el puerto 80/tcp
EXPOSE 80

#Ejecuta nuestra aplicacion cuando se inicia el contenedor
CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]